/**
 * Reads scraped history JSON and updates:
 * - README.md: section between <!-- youtube-recent-start --> and <!-- youtube-recent-end --> (last 5: thumb, title, author)
 * - youtube-watch-history.md: full list with title and author only.
 *
 * Usage: node update-docs.mjs <path-to-history.json>
 *   or:  cat history.json | node update-docs.mjs
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, '../..');
const README_PATH = resolve(REPO_ROOT, 'README.md');
const HISTORY_MD_PATH = resolve(REPO_ROOT, 'youtube-watch-history.md');

const START_MARKER = '<!-- youtube-recent-start -->';
const END_MARKER = '<!-- youtube-recent-end -->';

// Must match .github/workflows/youtube-history.yml schedule (e.g. "0 8 * * *" => 08:00 UTC).
const CRON_UTC_HOUR = 1;
const CRON_UTC_MINUTE = 0;
const TZ_BRAZIL = 'America/Sao_Paulo';

function getSyncTimes() {
  const now = new Date();
  const nextUtc = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate(), CRON_UTC_HOUR, CRON_UTC_MINUTE, 0, 0));
  if (now >= nextUtc) nextUtc.setUTCDate(nextUtc.getUTCDate() + 1);
  const opts = { timeZone: TZ_BRAZIL, dateStyle: 'short', timeStyle: 'short', hour12: false };
  const fmt = new Intl.DateTimeFormat('pt-BR', opts);
  return {
    lastSync: fmt.format(now),
    nextSync: fmt.format(nextUtc),
  };
}

function loadHistory(inputPath) {
  let raw;
  if (inputPath) {
    raw = readFileSync(inputPath, 'utf8');
  } else {
    raw = readFileSync(0, 'utf8');
  }
  const data = JSON.parse(raw);
  return Array.isArray(data) ? data : [];
}

function buildRecentSection(entries, syncTimes) {
  const recent = entries.slice(0, 5);
  const syncLine = `*Last synced: ${syncTimes.lastSync} (Brasília) · Next sync: ~${syncTimes.nextSync} (Brasília)*`;
  if (recent.length === 0) {
    return `\n${syncLine}\n\n*(No recent history.)*\n`;
  }
  const lines = [
    '',
    syncLine,
    '',
    '| | Title | Author |',
    '|---|------|--------|',
  ];
  for (const e of recent) {
    const link = `https://www.youtube.com/watch?v=${e.id}`;
    const thumb = `[![thumb](${e.thumbnailUrl})](${link})`;
    const titleLink = `[${escapePipe(e.title)}](${link})`;
    const author = escapePipe(e.author || '—');
    lines.push(`| ${thumb} | ${titleLink} | ${author} |`);
  }
  lines.push('');
  return lines.join('\n');
}

function escapePipe(s) {
  return String(s).replace(/\|/g, '\\|').replace(/\n/g, ' ');
}

function updateReadme(newContent) {
  const readme = readFileSync(README_PATH, 'utf8');
  const startIdx = readme.indexOf(START_MARKER);
  const endIdx = readme.indexOf(END_MARKER);

  let nextReadme;
  if (startIdx !== -1 && endIdx !== -1 && endIdx > startIdx) {
    const before = readme.slice(0, startIdx + START_MARKER.length);
    const after = readme.slice(endIdx);
    nextReadme = before + '\n' + newContent + '\n' + after;
  } else {
    const insertBefore = '## Get in touch';
    const idx = readme.indexOf(insertBefore);
    const insert = idx !== -1
      ? readme.slice(0, idx).trimEnd() +
        '\n\n---\n\n## Recently watched (YouTube)\n\n' +
        START_MARKER + newContent + '\n' + END_MARKER +
        '\n\n---\n\n' + readme.slice(idx)
      : readme + '\n\n## Recently watched (YouTube)\n\n' + START_MARKER + newContent + '\n' + END_MARKER + '\n';
    nextReadme = insert;
  }

  writeFileSync(README_PATH, nextReadme, 'utf8');
}

function writeHistoryMd(entries, syncTimes) {
  const header = `# YouTube watch history

Generated by \`scripts/youtube-history/run.mjs\`. Title and author only.

**Last synced:** ${syncTimes.lastSync} (horário de Brasília) · **Next sync:** ~${syncTimes.nextSync} (horário de Brasília)

| Title | Author |
|-------|--------|
`;
  const rows = entries.map((e) => `| ${escapePipe(e.title)} | ${escapePipe(e.author || '—')} |`);
  writeFileSync(HISTORY_MD_PATH, header + rows.join('\n') + '\n', 'utf8');
}

function main() {
  const inputPath = process.argv[2] || null;
  const entries = loadHistory(inputPath);
  const syncTimes = getSyncTimes();

  const recentContent = buildRecentSection(entries, syncTimes);
  updateReadme(recentContent);
  writeHistoryMd(entries, syncTimes);
}

main();
